name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.7
    - name: Restore dependencies
      run: dotnet restore
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile
    #- name: Zip
      #uses: montudor/action-zip@v1.0.0
      #with:
        #args: zip -qq -r 
